"""add alternative assets logic columns

Revision ID: ce12def4114e
Revises: f2c1ee7e690d
Create Date: 2026-01-24 13:45:18.991107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce12def4114e'
down_revision: Union[str, None] = 'f2c1ee7e690d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('portfolio_role', sa.String(length=30), nullable=True))
    op.add_column('insights', sa.Column('health_score', sa.Integer(), nullable=True))
    op.add_column('insights', sa.Column('profile_fit_score', sa.Integer(), nullable=True))
    op.add_column('insights', sa.Column('alternatives', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insights', 'alternatives')
    op.drop_column('insights', 'profile_fit_score')
    op.drop_column('insights', 'health_score')
    op.drop_column('insights', 'portfolio_role')
    # ### end Alembic commands ###
