"""add portfolio persistence fields and insight FK

Revision ID: f2c1ee7e690d
Revises: aece2f6fce3d
Create Date: 2026-01-24 08:58:39.178863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c1ee7e690d'
down_revision: Union[str, None] = 'aece2f6fce3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('portfolio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'insights', 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
    op.add_column('portfolios', sa.Column('overall_risk', sa.String(length=20), nullable=True))
    op.add_column('portfolios', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'summary')
    op.drop_column('portfolios', 'overall_risk')
    op.drop_constraint(None, 'insights', type_='foreignkey')
    op.drop_column('insights', 'portfolio_id')
    # ### end Alembic commands ###
